# Generated by Django 4.0.1 on 2022-07-20 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_video_delete_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='videoFile',
            new_name='video',
        ),
    ]
