# Generated by Django 4.0.1 on 2022-07-21 16:37

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='videos/', validators=[webapp.models.validate_file_extension]),
        ),
    ]
