# Generated by Django 4.0.1 on 2022-07-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_video_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='date',
        ),
    ]
